<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DES.Core\DES.Core.csproj" />
    <ProjectReference Include="..\DES.Feistel\DES.Feistel.csproj" />
    <ProjectReference Include="..\DES.Des\DES.Des.csproj" />
    <ProjectReference Include="..\DES.Deal\DES.Deal.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
